[book]
title = "Topographic Robot Documentation"
description = "An advanced terrain-mapping robot designed to traverse various landscapes"
authors = ["Brighton Sikarskie", "Matthew Manginelli", "Jeremie Hews"]
language = "en"
multilingual = false

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/Documentation/"
git-repository-url = "https://github.com/Topographic-Robot/Documentation"
git-repository-icon = "fa-github"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
